
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: install mysql python libraries
  ansible.builtin.pip:
   executable: pip3.9
   name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL

- name: java and maven setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java_setup.yaml


- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml
