- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml