- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup.yaml

- name: copy mongo repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present 

- name: connect mongodb {{ component }}
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('{{ component }}')"
  register: "{{ component }}_output"

- name: print {{ component }} output
  ansible.builtin.debug:
    msg: "{{ {{ component }}_output }}"

- name: load the {{ component }} products into mongodb
  ansible.builtin.shell:  mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: "{{ component }}_output.stdout | int < 0"

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml